### ISSUE TITLE
Add fuzzing feature to trace macro

### ISSUE THREAD

**Issue by sinui0** [privacy-ethereum/mpz#1]
In our `mpc-circuits` crate we have a macro for generating a circuit from Rust code, and we have another macro for testing the circuit against that code for conformity.

We should add an argument to the `trace` macro to generate fuzz targets which tests conformity for us. Should be pretty simple.

**Comment by matsutakk** [comment]
Hi, I want to work on this as GFE.

is it like below and shouldn't I use cargo-fuzz?

```rust
struct TraceConfig {
    cache: bool,
    suffix: String,
    fuzz_target: bool, // New field for fuzz target generation
}
```

**Comment by sinui0** [comment]
This is more involved than I initially thought when I wrote the issue. The fuzz targets should go into a separate crate, so this can't be done directly with a macro.

Additionally, the existing macros themselves are going to be replaced/deprecated so unfortunately I'm going to close this issue. Thank you anyhow!

**Comment by matsutakk** [comment]
Okay, thanks. I will look for another one, say, #21.

**Comment by matsutakk** [comment]
Thanks. I will look for another one, say #22.
