### ISSUE TITLE
Check if KOS15 security guarantees hold in practice

### ISSUE THREAD

**Issue by th4s** [privacy-ethereum/mpz#10]
At the moment it seems that KOS15 security is broken, c.f. https://eprint.iacr.org/2022/192
It has to be examined if we need to switch to a different OT extension protocol later.

Further more, currently there are not enough tests for the inner workings and logic of KOS15. It would be good to add some more, especially for the inner [utils module](https://github.com/tlsnotary/tlsn/blob/dev/mpc-core/src/ot/extension/kos15/utils.rs).

**Comment by th4s** [comment]
KOS15 paper recently got an update on how to fix it using SoftSpokenOT: https://eprint.iacr.org/2015/546

**Comment by themighty1** [comment]
the opinion of a libOTe maintainer about the KOS attack:
https://github.com/osu-crypto/libOTe/issues/87

**Comment by themighty1** [comment]
emp-ot author says the attack does not apply
https://github.com/emp-toolkit/emp-ot/issues/77

**Comment by ladnir** [comment]
FYI https://eprint.iacr.org/2022/1371

**Comment by themighty1** [comment]
https://eprint.iacr.org/2022/1371 was updated recently. KOS security proof remains broken.

**Comment by ladnir** [comment]
While I agree that Softspoken is the preferred solution, I don't see where in 1371 it states that KOS is broken. Care to give more information? Quoting the last paragraph

> The lower-bound established by our Corollary 3.14, which applies to KOS ... We emphasize that Roy’s attack on PSS is not known to apply to KOS. Rather, the opposite is true; our defense of KOS applies to PSS. The security of KOS thus resides somewhere between the lower-bound established by our Theorem 3.9 and the upper-bound achieved by Roy’s subfield attack. In any case, our result furnishes the only currently-known lower-bound for KOS, and its only proof of security. We leave the task of exactly settling KOS’s security to future work. In the meantime, we suggest that an alternative known to be concretely secure—like Roy’s SoftSpokenOT [Roy22]—be used when possible.

**Comment by themighty1** [comment]
@ladnir, thanks for sharing your opinion. I did not mean that **KOS itself** is broken, only that its **security proof** remains broken.
1371 proves that KOS is secure when the `k` is set to at least 5243. 

So, esentially we are back to square one like it was before Roy's paper was released: KOS still doesn't have a full security proof for practical values of `k` like 128.

Do you agree with this assessment?
Thanks.

**Comment by ladnir** [comment]
I see, for 128-bit security the concrete parameters are unclear. makes sense. Many works only prove asymptotics but I suppose in this case the concrete security seems more suspect than is typical.  Best to switch to SoftSpoken.
