### ISSUE TITLE
Parallelize garbled circuit generation/evaluation

### ISSUE THREAD

**Issue by sinui0** [privacy-ethereum/mpz#11]
Presently our generator implementation processes gates sequentially. I believe there is an opportunity to parallelize this processing by batching the gates into "levels" which do not have wire interdependencies.

The first step in this enhancement is to validate the assumption that these batches are large enough to justify the additional overhead from multithreading.

**Comment by themighty1** [comment]
I believe the depth of the circuit are those independent levels. The depths are indicated here https://homes.esat.kuleuven.be/~nsmart/MPC/
However, it seems that saturating the CPU by running garbling/evaluation of multiple circuits in parallel is an easier target.

**Comment by sinui0** [comment]
Completely agree, parallelizing across circuits is an easy win. On further thought, perhaps there is potential to parallelize both

The [hash_tweak](https://github.com/ProofOfProvenance/pop/blob/2b8dc97183b79ce71ee9cb8cb1852c9129b05a5c/pop-mpc-core/src/block.rs#L39) function currently hashes labels sequentially. The RustCrypto AES block cipher implementation can process blocks in batches, depending on the hardware. Up to 8 blocks at a time I believe. So we could potentially cut down hashing time up to a factor of 8 if we are processing independent gates in parallel as well. I was originally thinking spreading gates across threads, but this optimization would be single threaded.

**Comment by themighty1** [comment]
I couldnt understand how the AES soft implementation batches the blocks, here
https://github.com/RustCrypto/block-ciphers/blob/423945db3b2462d653a3257f3b508242a8ec4793/aes/src/soft/fixslice32.rs#L301

it says "Encrypts four blocks in-place and in parallel." but I don't see the "in parallel" part in the code.

But yes, if somehow batching would be possible in wasm, then AES would be a winner over Salsa.

**Comment by sinui0** [comment]
I believe the comment is a typo, the 32bit memory implementation can only do 2 blocks at a time. I haven't looked much into wasm64 but maybe it would be 2x faster?

[Here](https://github.com/RustCrypto/block-ciphers/blob/423945db3b2462d653a3257f3b508242a8ec4793/aes/src/soft/fixslice32.rs#L304) it loads 2 blocks into the state buffer and as far as I can tell it processes them both at once. Parallel may be the wrong word here, perhaps concurrent is more accurate.

[The NI version](https://github.com/RustCrypto/block-ciphers/blob/423945db3b2462d653a3257f3b508242a8ec4793/aes/src/ni/aes128.rs#L30) does 8 at once.

**Comment by sinui0** [comment]
Investing too much time at this stage is pre-mature optimization, but I was curious yesterday and checked it out real quick. 

Work is in the [circuit-preprocessing branch](https://github.com/ProofOfProvenance/pop/tree/circuit-preprocessing). It needs more testing and cleaner implementation before merging.

[I wrote a function](https://github.com/ProofOfProvenance/pop/blob/b61b7a37684c470849ff5108b3901673d6e3024c/pop-mpc-core/src/circuit/mod.rs#L118) which pre-processes boolean circuits by mapping their gates into independent groups. The groups  have to be computed sequentially but the gates within can be computed in parallel. This preprocessing only has to be done once and can be stored on disk.

Initial testing showed a 30% reduction in time to garble aes_128_reverse when using RustCrypto's AES NI "parallel" implementation on my machine. I haven't yet tried processing XOR gates using multithreading but for this circuit I suspect it is not worth it with an average of 98 gates per level. The same can be said about AND gates. It may be a different case for circuits which have very wide levels.

The aes_128_reverse circuit is 308 levels deep and has the following profile:
<img src=https://user-images.githubusercontent.com/65924192/156639231-0ff6a637-bd24-43f9-afd5-70750f319364.png width=800 />

<img src=https://user-images.githubusercontent.com/65924192/156639346-59e0c4d9-c64d-4486-99c6-de8663150e02.png width=800 />

**Comment by themighty1** [comment]
NIce work!
