### ISSUE TITLE
bug(mpz-garble-core): unit test does not test 0-0 case

### ISSUE THREAD

**Issue by sinui0** [privacy-ethereum/mpz#118]
https://github.com/privacy-scaling-explorations/mpz/blob/eed88d141b8cc81e58ddac20abffa70fc4481d29/garble/mpz-garble-core/src/lib.rs#L100

Our AND gate unit test does not test the 0-0 input case for a gate.

**Comment by caglaryucekaya** [comment]
Can I work on this?
