### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by xiangxiecrypto** [privacy-ethereum/mpz#170]
1. The current version forces to use `nightly` rustc, because of the use of `.first_chunk_mut()`. See [here](https://github.com/privacy-scaling-explorations/mpz/blob/dev/crates/mpz-common/src/executor/mt.rs#L316)
2. When I use unstable rustc, it complains that ``unknown feature stdsimd``

My environment: 
1. MacBook Pro M1. 
2. rustc version: 1.76.0

**Comment by th4s** [comment]
Updating your Rust version to use the current stable version 1.79 by doing `rustup update stable` should fix this.

**Comment by xiangxiecrypto** [comment]
solved
