### ISSUE TITLE
Synchronize Rayon Max Threads with MT Executor

### ISSUE THREAD

**Issue by th4s** [privacy-ethereum/mpz#178]
In order to prevent deadlocks it is important that the [number of parallel rayon threads](https://docs.rs/rayon/latest/rayon/struct.ThreadPoolBuilder.html#method.num_threads) is synchronized with the [MT executor's number of threads](https://github.com/privacy-scaling-explorations/mpz/blob/dev/crates/mpz-common/src/executor/mt.rs#L15).

One approach to do this would be to use local [`ThreadPools`](https://docs.rs/rayon/latest/rayon/struct.ThreadPool.html) which are owned by [`MTContext`](https://github.com/privacy-scaling-explorations/mpz/blob/dev/crates/mpz-common/src/executor/mt.rs#L92).
It is **important** that there is a way to inject different types of threadpools to support browser environments.

**Comment by sinui0** [comment]
https://github.com/RReverser/wasm-bindgen-rayon/issues/18

**Comment by sinui0** [comment]
Closing, instead we've moved away from putting logical threads on the global rayon pool. Each logical thread has it's own system thread. See #187
