### ISSUE TITLE
Missing trait implementations for `ShareConversionVerify` and `ShareConversionReveal`

### ISSUE THREAD

**Issue by th4s** [privacy-ethereum/mpz#32]
Currently both traits are not implemented. Instead the `ConverterSender` and `ConverterReceiver` publicly expose `verify` and `reveal` methods.

We should either remove the traits or implement them and make the member functions private.

**Comment by saeyoon17** [comment]
Hi, is this issue still valid? If it is, I would like to give it a try.

**Comment by th4s** [comment]
Hi there :) Just looked into this issue again and it is still valid. We have these traits but do not use them. We probably forgot to implement them for some reason. Thanks, will have a look at the PR soon.
