### ISSUE TITLE
Refactor out dispatch from `clmul`

### ISSUE THREAD

**Issue by sinui0** [privacy-ethereum/mpz#44]
Right now the clmul crate has to `match` on whether instrinsics are available for *every operation*, incurring significant overhead.

https://github.com/privacy-scaling-explorations/mpz/blob/a2007e628e1bc52722a3286b1ba053f5d55e2b7e/clmul/src/backend.rs#L86-L124

We should be able to factor this out using the [original approach from the polyval crate](https://github.com/RustCrypto/universal-hashes/blob/master/polyval/src/backend/autodetect.rs) with [`Union`](https://doc.rust-lang.org/reference/items/unions.html)

**Comment by themighty1** [comment]
will that mean also using `unsafe` like they do ?

**Comment by sinui0** [comment]
Yes, we will have to understand how to safely use `Union` as it is marked `unsafe`.

They `polyval` crate demonstrates how to do this
