### ISSUE TITLE
Add `miri` tests to CI

### ISSUE THREAD

**Issue by sinui0** [privacy-ethereum/mpz#45]
Crates containing unsafe code should be tested using [`miri`](https://github.com/rust-lang/miri) in our CI.

**Comment by 000wan** [comment]
I have a question with this; should we test for all unit tests, or only codes with `unsafe`? Testing with miri is slow especially for Circuits, so I wonder which ones to test and ones to skip. @sinui0

**Comment by sinui0** [comment]
Interesting, I wasn't aware how substantially `miri` slows down test execution. For now I think it would suffice to only run miri for crates/tests which contain unsafe blocks. In particular, for now, let's just run it for `clmul` and `matrix-transpose`
