### ISSUE TITLE
KOS state protection

### ISSUE THREAD

**Issue by sinui0** [privacy-ethereum/mpz#55]
In the [sender](https://github.com/privacy-scaling-explorations/mpz/blob/a98fd8a0997302ab5cafa88a8825f15990edf321/ot/mpz-ot/src/kos/sender.rs#L245-L301) setup procedure, replace the state with an error before attempting the cointoss.

**Comment by sheagrief** [comment]
@sinui0 
Hi, is this issue still open?
May I work on it?

**Comment by sinui0** [comment]
Yes, it's open and a simple one!
