### ISSUE TITLE
Adapt replay protocol for malicious security of share-conversion

### ISSUE THREAD

**Issue by th4s** [privacy-ethereum/mpz#6]
Modify the [current implementation](https://github.com/tlsnotary/tlsn/blob/dev/mpc/share-conversion-aio/src/gf2_128/recorder.rs#L44-L72) so that each individual OT choice is checked for correctness. Currently only the end result is checked.

Furthermore add a commitment to the sender's rng seed, which is revealed and checked in the end, when the tape is sent.

**Comment by heeckhau** [comment]
@th4s `recorder.rs` no longer exists.
Can this issue be close?

**Comment by th4s** [comment]
I would leave this open. The file has been renamed to `tape.rs`. I looked into it, and it seems that there is still no commitment to the sender's rng seed and only the final field element is checked for correctness.

**Comment by themighty1** [comment]
we don't use the tape anymore. @th4s , could pls confirm and if so, close this issue.

**Comment by th4s** [comment]
yes, closing it.
