### ISSUE TITLE
Support garbling with Salsa20

### ISSUE THREAD

**Issue by themighty1** [privacy-ethereum/mpz#70]
Currently we use AES for garbling which is very performant with AES-NI hardware acceleration. 
In the wasm environment, however, AES-NI is not available and we fall back to a software AES impl.

Edit: benchmarks had a bug, Salsa is actually 4x slower in wasm, i.e. in the same ballpark as AES in wasm.
~~Salsa20 outperforms software AES in wasm by a factor of 2.5x-3x~~
~~Previously benchmarked here https://github.com/tlsnotary/tlsn/issues/1#issuecomment-1046137977 (compare the lines AES vs Salsa)~~

**Comment by themighty1** [comment]
The literature describing garbling with a fixed-key AES conjectures that it is a random permutation. 
Acc.to this the 3rd comment in https://crypto.stackexchange.com/a/60499, Chacha is not widely conjectured to be a random permutation.

Also, recent work shows that 17-round ChaCha20 is not a random permutation.  
https://eprint.iacr.org/2020/1049

Makes sense to stick with AES for garbling.

(Also, the benchmarks were wrong. In fact Salsa and AES in wasm are approx. same speed)

**Comment by sinui0** [comment]
Thanks for researching this, nonetheless
